### ISSUE TITLE
where can I put the model files so it won't be downloading it from huggingface.co

### ISSUE THREAD

**Issue by reddhu** [TabbyML/tabby#118]
### **I don't have internet connection on the machine I am about to deploy this project. May I know where should I put the TabbyML/J-350M files so I can successfully run the docker image? Now it's giving me  the error message:**
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /TabbyML/J-350M/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8ac76d3430>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/TabbyML/J-350M/resolve/main/tokenizer_config.json
^CTraceback (most recent call last):
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1247, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Cannot find the requested files in the disk cache and outgoing traffic has been disabled. To enable hf.co look-ups and downloads online, set 'local_files_only' to False.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/app/tabby/tools/download_models.py", line 41, in <module>
    preload(local_files_only=args.prefer_local_files)
  File "/home/app/tabby/tools/download_models.py", line 26, in preload
    AutoTokenizer.from_pretrained(args.repo_id, local_files_only=local_files_only)
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 634, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 896, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/transformers/configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/transformers/utils/hub.py", line 443, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like TabbyML/J-350M is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by wsxiaoys** [comment]
Hi, @reddhu ,

You might prepare the `data` dir on a machine with internet access (with `docker run`), then you can copy it to your actual deploy environment.

**Comment by reddhu** [comment]
Hi @wsxiaoys 

**Thank you for your help. Now it's up and running. But when I send the curl request example to the server, it gives an unexpected error. I wonder if it has anything to do with my internet connection. Appreciate it if you can give me any advice on this showing error.**

curl:
curl -X POST http://localhost:5000/v1/completions -H 'Content-Type: application/json' --data '{
    "prompt": "def binarySearch(arr, left, right, x):\n    mid = (left +"
}'


2023-04-26 03:04:25,239 DEBG 'server' stderr output:
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/app/tabby/server/__init__.py", line 57, in completions
    response = model_backend(request)
  File "/home/app/tabby/server/backend/triton.py", line 91, in __call__
    choices = self.generate(data)
  File "/home/app/tabby/server/backend/triton.py", line 73, in generate
    result = self.client.infer(model_name, inputs)
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/tritonclient/grpc/__init__.py", line 1469, in infer
    raise_error_grpc(rpc_error)
  File "/home/app/.pyenv/versions/3.10.10/lib/python3.10/site-packages/tritonclient/grpc/__init__.py", line 75, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: Connection refused

**Comment by wsxiaoys** [comment]
Hi @reddhu

Could you give it another try with latest released lark version?
