### ISSUE TITLE
Error occurs about tabby-python-client

### ISSUE THREAD

**Issue by HeroSong666** [TabbyML/tabby#1624]
when i follow the steps in:
https://github.com/TabbyML/tabby/tree/a07a070fa97c270b192151e14fd60b538ef666ff/python/tabby-eval/modal/tabby_python_client ,
i run the following code in the path:  /tabby-main/python/tabby-eval/modal/tabby_python_client/:

from tabby_python_client import AuthenticatedClient

client = AuthenticatedClient(base_url="https://api.example.com/", token="SuperSecretToken")

from tabby_python_client.models import MyDataModel
from tabby_python_client.api.my_tag import get_my_data_model
from tabby_python_client.types import Response

my_data: MyDataModel = get_my_data_model.sync(client=client)
response: Response[MyDataModel] = get_my_data_model.sync_detailed(client=client)

client = AuthenticatedClient(
base_url="https://internal_api.example.com/",
token="SuperSecretToken",
verify_ssl="/path/to/certificate_bundle.pem",
)

it returns:

Traceback (most recent call last):
File "/ASR/tabby-main/python/tabby-eval/modal/tabby_python_client/pytabby.py", line 5, in
from tabby_python_client.models import MyDataModel
ImportError: cannot import name 'MyDataModel' from 'tabby_python_client.models' (/ASR/tabby-main/python/tabby-eval/modal/tabby_python_client/tabby_python_client/models/init.py)

**Comment by HeroSong666** [comment]
when i follow the steps in https://github.com/TabbyML/tabby/tree/a07a070fa97c270b192151e14fd60b538ef666ff/python/tabby-eval/modal/tabby_python_client ,i run the following code in the path:/tabby-main/python/tabby-eval/modal/tabby_python_client/:

from tabby_python_client import AuthenticatedClient

client = AuthenticatedClient(base_url="https://api.example.com", token="SuperSecretToken")

from tabby_python_client.models import MyDataModel
from tabby_python_client.api.my_tag import get_my_data_model
from tabby_python_client.types import Response

my_data: MyDataModel = get_my_data_model.sync(client=client)
# or if you need more info (e.g. status_code)
response: Response[MyDataModel] = get_my_data_model.sync_detailed(client=client)

client = AuthenticatedClient(
    base_url="https://internal_api.example.com", 
    token="SuperSecretToken",
    verify_ssl="/path/to/certificate_bundle.pem",
)

it returns:

Traceback (most recent call last):
  File "/ASR/tabby-main/python/tabby-eval/modal/tabby_python_client/pytabby.py", line 5, in <module>
    from tabby_python_client.models import MyDataModel
ImportError: cannot import name 'MyDataModel' from 'tabby_python_client.models' (/ASR/tabby-main/python/tabby-eval/modal/tabby_python_client/tabby_python_client/models/__init__.py)

**Comment by HeroSong666** [comment]
I am new to tabby, and i try to build a python api for the tabby server so that I can access the server through python and chat. (rather than through the Playground chat box)

**Comment by wsxiaoys** [comment]
The `tabby_python_client` is private to `tabby-eval` and should not be considered stable as an SDK.

For API usage, please refer directly to our REST API documentation: https://tabby.tabbyml.com/api

**Comment by HeroSong666** [comment]
> The `tabby_python_client` is private to `tabby-eval` and should not be considered stable as an SDK.
> 
> For API usage, please refer directly to our REST API documentation: https://tabby.tabbyml.com/api

I've checked this website, but I have never been exposed to the plug-in API before.. Could you please tell me what the 
"completion", "event" and "health" means? Many thanks！

**Comment by HeroSong666** [comment]
> The `tabby_python_client` is private to `tabby-eval` and should not be considered stable as an SDK.
> 
> For API usage, please refer directly to our REST API documentation: https://tabby.tabbyml.com/api

At the same time, these plug-ins seem to only provide the code model API. If I want to use the code model and the chat model at the same time, can I only modify the playground API?
