### ISSUE TITLE
Linux binary fails to download model

### ISSUE THREAD

**Issue by ChiNoel-osu** [TabbyML/tabby#2156]
**Describe the bug**
I'm using the linux binary files, but it fails to download models when i run `serve --model` or `download --model`, despite HF returned HTTP 200.
STDOUT w/ `RUST_BACKTRACE=full`:
```
$ rm -r .tabby/
$ ./tabby_x86_64-manylinux2014 serve --model TabbyML/DeepseekCoder-1.3B
Writing to new file.
File exists. Resuming.
File exists. Resuming.
thread 'main' panicked at /__w/tabby/tabby/crates/tabby-download/src/lib.rs:167:25:
Failed to fetch model 'TabbyML/DeepseekCoder-1.3B' due to 'Fetching 'https://huggingface.co/TheBloke/deepseek-coder-1.3b-base-GGUF/resolve/main/deepseek-coder-1.3b-base.Q8_0.gguf' failed: Server returned 200 OK HTTP status'
stack backtrace:
   0:     0x555f6ddff506 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x555f6ddff506 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x555f6ddff506 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x555f6ddff506 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x555f6de309d0 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x555f6de309d0 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x555f6ddfb75f - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x555f6ddff2e4 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x555f6ddff2e4 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x555f6de00b67 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x555f6de008c9 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x555f6de00ff8 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x555f6de00ed2 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x555f6ddffa06 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x555f6de00c30 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x555f6c03ab75 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x555f6c1cb217 - tabby_download::download_model::{{closure}}::hab1249023fbf1b56
  17:     0x555f6c1f4674 - tabby::services::model::download_model_if_needed::{{closure}}::h58b73dd9bd0c0e5a
  18:     0x555f6c1f4c73 - tabby::serve::main::{{closure}}::h6f2489c87370aff8
  19:     0x555f6c1e7a21 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h4c69cfbd6cd4a356
  20:     0x555f6c1e7329 - tokio::runtime::park::CachedParkThread::block_on::h1c4015ba81f1e27d
  21:     0x555f6c10b231 - tabby::main::h9d656a0d31fbb30c
  22:     0x555f6c25adb3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h781cbb89105aef57
  23:     0x555f6c1d8349 - std::rt::lang_start::{{closure}}::hd5f9b9257539fa30
  24:     0x555f6ddf0dd1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  25:     0x555f6ddf0dd1 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  26:     0x555f6ddf0dd1 - std::panicking::try::h8bbf75149211aaaa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  27:     0x555f6ddf0dd1 - std::panic::catch_unwind::h8c78ec68ebea34cb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  28:     0x555f6ddf0dd1 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  29:     0x555f6ddf0dd1 - std::panicking::try::do_call::hcb3194972c74716d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  30:     0x555f6ddf0dd1 - std::panicking::try::hcdc6892c5f0dba4c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  31:     0x555f6ddf0dd1 - std::panic::catch_unwind::h4910beb4573f4776
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  32:     0x555f6ddf0dd1 - std::rt::lang_start_internal::h6939038e2873596b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  33:     0x555f6c10b445 - main
  34:     0x7f973cbbcd90 - <unknown>
  35:     0x7f973cbbce40 - __libc_start_main
  36:     0x555f6c0531de - <unknown>
  37:                0x0 - <unknown>
```

**Information about your version**
Ubuntu 22.04 LTS
tabby 0.11.1

**Information about your GPU**
CPU only.

**Additional context**
Windows executable works just fine on Windows 10 with the same command.

**Comment by boxbeam** [comment]
Please reopen another issue with the full error if you encounter this again
