### ISSUE TITLE
Tabby on modal FileNotFountError

### ISSUE THREAD

**Issue by Mootfrost777** [TabbyML/tabby#2177]
app.py from documentation fails to start with this error:

```

=> Step 0: running function 'download_model'
/root/app.py:35: DeprecationError: 2024-04-29: The use of "Stub" has been deprecated in favor of "App". This is a pure name change with no other implications.
  stub = Stub("tabby-server-" + MODEL_ID.split("/")[-1], image=image)
Traceback (most recent call last):
  File "/pkg/modal/_container_io_manager.py", line 487, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 239, in run_input_sync
    res = finalized_function.callable(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/app.py", line 15, in download_model
    subprocess.run(
  File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/tabby/bin/tabby-cpu'
```

**Comment by wsxiaoys** [comment]
Hi, could you confirm the image tag you were using? is it `0.11.1`?
