### ISSUE TITLE
IDE error in IntelliJ-Plugin which breaks the Plugin until restart

### ISSUE THREAD

**Issue by nailujx86** [TabbyML/tabby#3222]
**Describe the bug**
When using the cycle previous action an IDE error can occur, if no completionresults are loaded yet. This results in the plugin completely breaking and not responding until a full IDE restart occured.

**Information about your version**
IntelliJ Plugin 1.7.1

**Information about your GPU**
Please provide output of `nvidia-smi`
Doesn't apply.

**Additional context**
```
2024-09-30 10:27:17,830 [6969912] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - Unhandled exception in Dispatchers.IO
java.lang.ArithmeticException: / by zero
	at com.tabbyml.intellijtabby.completion.InlineCompletionService.calcCycleIndex(InlineCompletionService.kt:267)
	at com.tabbyml.intellijtabby.completion.InlineCompletionService.access$calcCycleIndex(InlineCompletionService.kt:35)
	at com.tabbyml.intellijtabby.completion.InlineCompletionService$cycle$1$job$1.invoke(InlineCompletionService.kt:337)
	at com.tabbyml.intellijtabby.completion.InlineCompletionService$cycle$1$job$1.invoke(InlineCompletionService.kt:333)
	at com.tabbyml.intellijtabby.completion.InlineCompletionService$launchJobForInlineCompletion$2.invokeSuspend(InlineCompletionService.kt:242)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.SoftLimitedDispatcher$Worker.run(SoftLimitedDispatcher.kt:125)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
2024-09-30 10:27:17,832 [6969914] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - IntelliJ IDEA 2024.2.3  Build #IC-242.23339.11
2024-09-30 10:27:17,832 [6969914] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - JDK: 21.0.4; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-09-30 10:27:17,832 [6969914] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - OS: Windows 10
2024-09-30 10:27:17,832 [6969914] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - Plugin to blame: Tabby version: 1.7.1
2024-09-30 10:27:17,832 [6969914] SEVERE - #c.i.o.a.i.CoroutineExceptionHandlerImpl - Last Action: Tabby.InlineCompletion.CyclePrevious
2024-09-30 10:27:17,842 [6969924]   INFO - #com.tabbyml.intellijtabby.lsp.LanguageClient - [TabbyAgent] Fetching completion canceled.
2024-09-30 10:27:17,850 [6969932]   INFO - STDERR - Exception in thread "DefaultDispatcher-worker-14" java.lang.ArithmeticException: / by zero
2024-09-30 10:27:17,850 [6969932]   INFO - STDERR - 	at com.tabbyml.intellijtabby.completion.InlineCompletionService.calcCycleIndex(InlineCompletionService.kt:267)
2024-09-30 10:27:17,850 [6969932]   INFO - STDERR - 	at com.tabbyml.intellijtabby.completion.InlineCompletionService.access$calcCycleIndex(InlineCompletionService.kt:35)
2024-09-30 10:27:17,850 [6969932]   INFO - STDERR - 	at com.tabbyml.intellijtabby.completion.InlineCompletionService$cycle$1$job$1.invoke(InlineCompletionService.kt:337)
2024-09-30 10:27:17,850 [6969932]   INFO - STDERR - 	at com.tabbyml.intellijtabby.completion.InlineCompletionService$cycle$1$job$1.invoke(InlineCompletionService.kt:333)
2024-09-30 10:27:17,850 [6969932]   INFO - STDERR - 	at com.tabbyml.intellijtabby.completion.InlineCompletionService$launchJobForInlineCompletion$2.invokeSuspend(InlineCompletionService.kt:242)
2024-09-30 10:27:17,850 [6969932]   INFO - STDERR - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-09-30 10:27:17,850 [6969932]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
2024-09-30 10:27:17,850 [6969932]   INFO - STDERR - 	at kotlinx.coroutines.internal.SoftLimitedDispatcher$Worker.run(SoftLimitedDispatcher.kt:125)
2024-09-30 10:27:17,850 [6969932]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
2024-09-30 10:27:17,850 [6969932]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
2024-09-30 10:27:17,850 [6969932]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
2024-09-30 10:27:17,850 [6969932]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
2024-09-30 10:27:17,850 [6969932]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
2024-09-30 10:27:17,851 [6969933]   INFO - STDERR - 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ca0a86a, Dispatchers.IO]
```

**Comment by icycodes** [comment]
Hi, @nailujx86 
Thank you for reporting this bug. The code did not check the parameters before the divide calculation. I will add a guard to fix it.

However, I am facing an issue when attempting to reproduce it. The cycling actions are disabled when no inline completion item is shown, so it should be safe to invoke cycling when no completion item is loaded. Could you provide detailed steps on how to reproduce this bug?

**Comment by nailujx86** [comment]
Hi @icycodes,
My plugin is not connecting locally but to a remote tabby server instance. I've faced this issue when switching lines/contexts and probably invoking the cycle-action before the plugin received any initial reply.

**Comment by nailujx86** [comment]
I wasn't able to reproduce this issue anymore with client version >= 1.8.1. Therefore I will close this issue. Thank you for your fix!
