### ISSUE TITLE
VSCode extension not working.

### ISSUE THREAD

**Issue by didip** [TabbyML/tabby#3248]
**Describe the bug**
VSCode extension not working. It seems to look for a pem file that does not exist?

```
Error: Invalid PEM formatted message.
    at QJ.decode (/Users/didip/.vscode/extensions/tabbyml.vscode-tabby-1.12.1/dist/tabby-agent/node/index.js:206:1480)
    at ZA.pemToDer (/Users/didip/.vscode/extensions/tabbyml.vscode-tabby-1.12.1/dist/tabby-agent/node/index.js:209:137473)
    at wj (/Users/didip/.vscode/extensions/tabbyml.vscode-tabby-1.12.1/dist/tabby-agent/node/index.js:221:57)
    at wj (/Users/didip/.vscode/extensions/tabbyml.vscode-tabby-1.12.1/dist/tabby-agent/node/index.js:221:190)
    at /Users/didip/.vscode/extensions/tabbyml.vscode-tabby-1.12.1/dist/tabby-agent/node/index.js:221:1969
    at Array.map (<anonymous>)
    at Object.Tj (/Users/didip/.vscode/extensions/tabbyml.vscode-tabby-1.12.1/dist/tabby-agent/node/index.js:221:1931)
    at Lj (/Users/didip/.vscode/extensions/tabbyml.vscode-tabby-1.12.1/dist/tabby-agent/node/index.js:381:408)
    at $m.preInitialize (/Users/didip/.vscode/extensions/tabbyml.vscode-tabby-1.12.1/dist/tabby-agent/node/index.js:381:665)
    at Qv.preInitialize (/Users/didip/.vscode/extensions/tabbyml.vscode-tabby-1.12.1/dist/tabby-agent/node/index.js:422:6382)
```

**Information about your version**
Please provide output of `tabby --version`
tabby 0.18.0
vscode extension: v1.12.1

**Information about your GPU**
Please provide output of `nvidia-smi`
Doesn't exist. This is MBP M3

**Additional context**

**Comment by Sma1lboy** [comment]
Sorry for the issue. I will take a look at this in the next few days.
