### ISSUE TITLE
Chat window fails to open when running tabby-agent in VSCodium

### ISSUE THREAD

**Issue by adjenks** [TabbyML/tabby#3465]
**Describe the bug**
Problem loading chat window in VSCodium.

**Information about your version**
1.14.0

**Information about your GPU**
n/a

**Additional context**
```
ReferenceError: ReadableStream is not defined
    at /ommitted/.vscodium-server/extensions/tabbyml.vscode-tabby-1.14.0-universal/dist/tabby-agent/node/index.js:263:14468
    at /ommitted/.vscodium-server/extensions/tabbyml.vscode-tabby-1.14.0-universal/dist/tabby-agent/node/index.js:46:587
    at /ommitted/.vscodium-server/extensions/tabbyml.vscode-tabby-1.14.0-universal/dist/tabby-agent/node/index.js:263:27607
    at /ommitted/.vscodium-server/extensions/tabbyml.vscode-tabby-1.14.0-universal/dist/tabby-agent/node/index.js:46:587
    at /ommitted/.vscodium-server/extensions/tabbyml.vscode-tabby-1.14.0-universal/dist/tabby-agent/node/index.js:264:6059
    at /ommitted/.vscodium-server/extensions/tabbyml.vscode-tabby-1.14.0-universal/dist/tabby-agent/node/index.js:46:587
    at Object.<anonymous> (/ommitted/.vscodium-server/extensions/tabbyml.vscode-tabby-1.14.0-universal/dist/tabby-agent/node/index.js:476:3704)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)

2024-11-25 22:03:57.242 [info] [Error - 10:03:57 PM] Server process exited with code 1.
2024-11-25 22:03:57.247 [info] [Error - 10:03:57 PM] Server initialization failed.
2024-11-25 22:03:57.247 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2024-11-25 22:03:57.247 [info] [Info  - 10:03:57 PM] Connection to server got closed. Server will restart.
2024-11-25 22:03:57.247 [info] true
2024-11-25 22:03:57.250 [info] [Error - 10:03:57 PM] Handling connection close failed
2024-11-25 22:03:57.250 [info] Error: Method not implemented.
	at fu.clear (/ommitted/.vscodium-server/extensions/tabbyml.vscode-tabby-1.14.0-universal/dist/node/extension.js:71:4250)
	at Sh.cleanUp (/ommitted/.vscodium-server/extensions/tabbyml.vscode-tabby-1.14.0-universal/dist/node/extension.js:61:9458)
	at Sh.handleConnectionClosed (/ommitted/.vscodium-server/extensions/tabbyml.vscode-tabby-1.14.0-universal/dist/node/extension.js:61:13424)
2024-11-25 22:03:57.250 [info] [Error - 10:03:57 PM] Tabby client: couldn't create connection to server.
2024-11-25 22:03:57.250 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by icycodes** [comment]
Hi @adjenks,

Could you please check your VSCodium version? The error in logs seems to be a Node.js version compatibility issue. The Tabby extension requires VSCodium version > 1.82.0 (with Node.js > 18).

**Comment by adjenks** [comment]
@icycodes 
Version: 1.93.0
Electron: 30.4.0
ElectronBuildId: undefined
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0

**Comment by icycodes** [comment]
Hi @adjenks,

Thanks for providing the detailed version info.

I noticed that you might be using a remote development container, as the log shows that the Tabby extension is installed in `/.vscodium-server`. In this case, the extension is running in the dev container.

Could you please try the following:
1. Check if the Tabby extension can be initialized in a local workspace.
2. Check the VSCodium server version in the dev container.

**Comment by adjenks** [comment]
@icycodes No problem. Thank you for helping out here.

Yes it was running remotely. I use another extension "Open Remote - SSH installed" to do this.

Oh, It does seem to work fine if I open a new, non-remote window. I would like it to work on my remote projects though.
I'll add this to the title of this ticket since that is another important factor.

`./codium-server --version`

> 1.93.0
> 44560ce62f89cd33130676a7c21c22b476173a94
> x64

**Comment by WatchMeBakinWaffles** [comment]
Hello @adjenks

Are you having the same behavior as me there #3424 ? My context is devcontainer (which works very similarly as remote ssh).

**Comment by adjenks** [comment]
@WatchMeBakinWaffles I was running the latest tabby docker container on a remote server and connecting to a different server with Open Remote - SSH.
