### ISSUE TITLE
Randomly get Parsing the query failed: SyntaxError

### ISSUE THREAD

**Issue by katopz** [TabbyML/tabby#650]
**Describe the bug**
1. New file named `test.rs`.
2. Type `// Hello world code in Rust`.
3. ...Not sure but it's randomly happen.

**Information about your GPU**
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.98       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:01:00.0  On |                  Off |
|  0%   44C    P8              39W / 450W |  23093MiB / 24564MiB |     13%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        12      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+
```

**Additional context**
> Run
```bash
sudo docker run -it --gpus all -p 9090:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/Mistral-7B --device cuda
2023-10-26T15:33:25.354011Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:143: Starting server, this might takes a few minutes...
2023-10-26T15:33:25.361516Z  INFO tabby::serve::search: crates/tabby/src/serve/search.rs:190: Index is ready, enabling server...
2023-10-26T15:33:45.017224Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:161: Listening at 0.0.0.0:8080
```

> Error log
```bash
thread 'tokio-runtime-worker' panicked at crates/tabby/src/serve/search.rs:125:14:
Parsing the query failed: SyntaxError("language:rust AND ( )")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at crates/tabby/src/serve/search.rs:125:14:
Parsing the query failed: SyntaxError("language:rust AND (   )")
thread 'tokio-runtime-worker' panicked at crates/tabby/src/serve/search.rs:125:14:
Parsing the query failed: SyntaxError("language:plaintext AND ( )")
thread 'tokio-runtime-worker' panicked at crates/tabby/src/serve/search.rs:125:14:
Parsing the query failed: SyntaxError("language:plaintext AND (  )")
thread 'tokio-runtime-worker' panicked at crates/tabby/src/serve/search.rs:125:14:
Parsing the query failed: SyntaxError("language:plaintext AND (   )")
```

This could be minor (maybe just warning?) and less concern because I still got the completion result just not sure what causing this.

**Comment by wsxiaoys** [comment]
Which version are you running at? (tabby --version), this issue should've been fixed in recent release

**Comment by katopz** [comment]
Seem to be at `0.3.0` 👍
